# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ACTWelljoinedClass' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
	pod 'Firebase/Core'

pod 'Firebase/Auth'
pod 'Firebase/Database'

end

target 'ACTWelljoinedClass-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ACTWelljoinedClass-tvOS

  target 'ACTWelljoinedClass-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
