export default {
  FETCH_LIST_COURSES: "APP/FETCH_LIST_COURSES",
  FETCH_LISTSTUDENT_BY_COURSEID: "APP/FETCH_LISTSTUDENT_BY_COURSEID",
  SELECTED_COURSE: "APP/SELECTED_COURSE",
  SAVE_ACCOUNT_FB: "APP/SAVE_ACCOUNT_FB",
  LOGIN: {
    MESSAGE_SUSCESS: "success",
    GET_ACCOUT_ADMIN_SUSCESS: "APP/GET_ACCOUNT_ADMIN_SUSCESS",
    GET_ACCOUT_ADMIN_FAILURE: "APP/GET_ACCOUT_ADMIN_FAILURE"
  }
};
