export default {
  FETCH_LIST_COURSES: "APP/FETCH_LIST_COURSES",
  FETCH_LISTSTUDENT_BY_COURSEID: "APP/FETCH_LISTSTUDENT_BY_COURSEID",
  SELECTED_COURSE: "APP/SELECTED_COURSE",
  SAVE_ACCOUNT_FB: "APP/SAVE_ACCOUNT_FB",
  iS_LOADING: "APP/IS_LOADING",
  LOGIN: {
    MESSAGE_SUSCESS: "success",
    GET_ACCOUT_ADMIN_SUSCESS: "APP/GET_ACCOUNT_ADMIN_SUSCESS",
    GET_ACCOUT_ADMIN_FAILURE: "APP/GET_ACCOUT_ADMIN_FAILURE",
    INSERT_NEW_STAFF: "APP/INSERT_NEW_STAFF"
  },
  LESSON: {
    LESSON_BY_COURSE_ID: "APP/LESSON_BY_COURSE_ID",
    GET_SELECTED_LESSON: "APP/GET_SELECTED_LESSON",
    GET_STUDENT_ATTENDANCE: "APP/GET_STUDENT_ATTENDANCE",
    INSERT_NEW_LESSON: "APP/INSERT_NEW_LESSON",
    RESET_NEWLESSON_MESS: "APP/RESET_NEWLESSON_MESS"
  },
  ATTENDANCE: {
    VALIDATE_LESSON: "ATTENDANCE/VALIDATE_LESSON",
    INSERT_NEW_STUDENT: "ATTENDANCE/INSERT_NEW_STUDENT"
  },
  STUDENT: {
    INSERT_NEW_STUDENT: "STUDENT/INSERT_NEW_STUDENT"
  }
};
